export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_GENRES = "GET_GENRES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_VIDEOGAME_BY_NAMES = "GET_VIDEOGAME_BY_NAMES";
export const GET_VIDEOGAME_BY_Id = "GET_VIDEOGAME_BY_ID";
export const POST_VIDEOGAME = "POST_VIDEOGAME";